title: Anthony Julien
description: Analyste de données |  Python • Power BI • SQL • GIS | Insights & Data storytelling
theme: jekyll-theme-cayman

show_downloads: false

github:
  is_project_page: false
